services:
  portfolio:
    build: .
    image: portfolio-img
    container_name: portfolio
    restart: unless-stopped
# if you dont want to use anubis
#    ports:
#      - "8080:7681" #http:ttyd
#
# exposing ttyd port only so anubis cant be bypassed
    expose:
      - "7681"
    read_only: true
    cap_drop:
      - ALL # strip root inside the container of his privileges 
    security_opt: 
      - no-new-privileges:true #forbid system from granting higher privileges if vulnerability is exploited
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M 

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    restart: unless-stopped
    environment:
      - TARGET=http://portfolio:7681
      - BIND=:8923
    depends_on:
      - portfolio

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - anubis

# uncomment for production to block the outbound internet access from inside the container
#  networks:
#      - net
#
#networks:
#  net:
#    internal: true


