services:
  portfolio:
    image: portfolio-img
    container_name: portfolio
    restart: unless-stopped

    ports:
      - "8080:7681" #http:ttyd

    read_only: true

    cap_drop:
      - ALL # strip root inside the container of his privileges 

    security_opt: 
      - no-new-privileges:true #forbid system from granting higher privileges if vulnerability is exploited

    tmpfs:
      - /tmp

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M 

# uncomment for production to block the outbound internet access from inside the container
#  networks:
#      - net
#
#networks:
#  net:
#    internal: true


